export const MetadataCardContainer = [
	{
		"@context": "https://schema.org",
		"@type": "ImageObject",
		"author": "Freepik",
		"contentLocation": "Courcelles, Belgique",
		"contentUrl": "/img/massage-sportif.webp",
		"datePublished": "2024-03-22",
		"description": "La main gauche du masseur prenant les muscles de l'épaule, afin de détendre la zone",
		"name": "un massage sportif afin de dénouer les contractures musculaires",
	},
    {
		"@context": "https://schema.org",
		"@type": "ImageObject",
		"author": "Freepik",
		"contentLocation": "Courcelles, Belgique",
		"contentUrl": "/img/massage-relaxant.webp",
		"datePublished": "2024-04-22",
		"description": "Les 2 mains du masseur sur les omoplates d'une jeune femme, la  massant endouceur afin de la relaxer",
		"name": "un massage relaxant afin de la détendre pleinement",
	},{
		"@context": "https://schema.org",
		"@type": "ImageObject",
		"author": "Freepik",
		"contentLocation": "Courcelles, Belgique",
		"contentUrl": "/img/shiatsu.webp",
		"datePublished": "2023-11-23",
		"description": "Les 2 mains du thérapeuthe shiatsu sous les omoplates d'une jeune femme habillée, travaillant de facon enérgétique",
		"name": "Une séance de shiatsu donné sur un futon",
	},{
		"@context": "https://schema.org",
		"@type": "ImageObject",
		"author": "Freepik",
		"contentLocation": "Courcelles, Belgique",
		"contentUrl": "/img/reiki.webp",
		"datePublished": "2023-11-23",
		"description": "Les 2 mains de la thérapeuthe reiki autour des tempes, lui donnant un soin",
		"name": "Une séance de reiki donné sur un futon à même le sol",
	},{
		"@context": "https://schema.org",
		"@type": "ImageObject",
		"author": "Freepik",
		"contentLocation": "Trazegnies, Belgique",
		"contentUrl": "/img/massage-sur-chaise.webp",
		"datePublished": "2023-09-23",
		"description": "Les 2 mains du masseur placées juste au-dessus des lombaires sur les muscles spinaux",
		"name": "Une séance de massage sur chaise (amma) donner au sein d'une entreprise",
	},{
		"@context": "https://schema.org",
		"@type": "ImageObject",
		"author": "Freepik",
		"contentLocation": "Trazegnies, Belgique",
		"contentUrl": "/img/reflexologie-plantaire.webp",
		"datePublished": "2022-10-26",
		"description": "Les 2 pouces massant la voute plantaire procurant une liberation des tensions",
		"name": "Une séance de réflexologie plantaire au sein de mon cabinet de massage",
	},{
		"@context": "https://schema.org",
		"@type": "ImageObject",
		"author": "Freepik",
		"contentLocation": "Trazegnies, Belgique",
		"contentUrl": "/img/massage-voyage-des-sens-mini.webp",
		"datePublished": "2024-05-08",
		"description": "Les 2 mains massant en douceur le dos permettant de liberer toutes les tensions",
		"name": "Voyage des sens est un massage qui permet de 'partir' loin pendant 2 heures",
	},
    {
		"@context": "https://schema.org",
		"@type": "ImageObject",
		"author": "Freepik",
		"contentLocation": "Courcelles, Belgique",
		"contentUrl": "/img/massage-ventouses-mini.webp",
		"datePublished": "2024-04-08",
		"description": "On voit le masseur faire glisser une ventouse au niveau des poignées d'amour pour faire réagir cette vilaine peau d'orange",
		"name": "C'est un massage effectué avec des ventouses qui vont permettre de déloger la cellulite",
	},{
		"@context": "https://schema.org",
		"@type": "ImageObject",
		"author": "Freepik",
		"contentLocation": "Courcelles, Belgique",
		"contentUrl": "/img/douceur-nuque.webp",
		"datePublished": "2024-04-09",
		"description": "Travail tres doux au niveau de la nuque afin de relacher les tensions",
		"name": "Une jeune femme se faisant masser la nuque en douceur",
	},
];
